### ISSUE TITLE
Latest Gemma M0 uf2 has mixes of CircuitPy 2 and 3

### ISSUE THREAD

**Issue by Saguine** [adafruit/circuitpython#1107]
Lines one and two of the default main.py found after flashing with this (https://github.com/adafruit/circuitpython/releases/download/3.0.0/adafruit-circuitpython-gemma_m0-3.0.0.uf2) are:

```
# Gemma IO demo
# Welcome to CircuitPython 2.0.0 :)
```

However, main.py throws a ValueError once flashed and does not run, until you replace the lib files from their respective .mpy files from version 3 (downloaded here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/tag/20180810).

It seems like the CircuitPy version is 3, but the libs and comments for the started project are outdated.

**Comment by dhalbert** [comment]
The https://github.com/adafruit/circuitpython/releases/download/3.0.0/adafruit-circuitpython-gemma_m0-3.0.0.uf2 is just CircuitPython. It does not overwrite CIRCUITPY, so it does not replace any older files that are already there, which might be outdated. So you need to update those yourself.

We might provide a .uf2 that's a factory-fresh load of 3.0.x that also replaces CIRCUITPY.

**Comment by Saguine** [comment]
Understood: I think I have a misunderstanding on what is and is not replaced. Thank you!

**Comment by dhalbert** [comment]
Just FYI, it's possible to save the entire contents of a non-Express board (Gemma, Trinket, Feather M0 Basic, etc.). If you copy CURRENT.UF2 when the ...BOOT drive is showing, that will be the entire contents of flash memory, including both CircuitPython and CIRCUITPY. This is handy if you want to back up the state of the whole board. This doesn't work on Express boards because CIRCUITPY is on the separate 2MB SPI flash chip.

But the normal CircuitPython .uf2 files only overwrite the part of flash memory they are meant to replace, so CIRCUITPY is preserved
