### ISSUE TITLE
long-lived UART buffer still not working right

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1126]
Following on #1056 and #1080, it appears that PR #1080 still has issues, depending on whether or not the code is imported from a file:

Tested on commit 2e80f37 on an M0 Adalogger:

REPL:
```
Adafruit CircuitPython 3.0.0-4-g2e80f37 on 2018-08-08; Adafruit Feather M0 Adalogger with samd21g18
>>> import board,busio
>>> uart = busio.UART(board.TX, board.RX)
>>> uart.write(b'\xbb')
1
```
But in a file:
file `test_uart.py`:
```
import board, busio
uart = busio.UART(board.TX, board.RX)
```
Now in REPL
```
Adafruit CircuitPython 3.0.0-4-g2e80f37 on 2018-08-08; Adafruit Feather M0 Adalogger with samd21g18
>>> import test_uart
>>> test_uart.uart.write(b'\xbb')
0
```
Nothing is written (see the 0 return above). Was originally testing with a Saleae, and confirmed that nothing gets written.

tagging @jepler

**Comment by jepler** [comment]
I'll try to take a look at this tonight. If I came provide a resolution then maybe the change needs to be reverted for now

**Comment by dhalbert** [comment]
The build that I tested against was too old, and did not include #1080. So I believe this is a red herring. Tested against cac760a, and UART seems to work fine.

@robomike could you retest with this build?
https://adafruit-circuit-python.s3.amazonaws.com/bin/feather_m0_adalogger/adafruit-circuitpython-feather_m0_adalogger-20180809-cac760a.bin

**Comment by jepler** [comment]
I don't have a Feather M0 datalogger, so I tested with a Feather M0 Express instead.

In order to make a test of both send and receive without getting out the 'scope, I placed a 220Ω resistor between the RX and TX pins.

With the above-shown content in `test_uart.py`, I opened the repl:
```
Adafruit CircuitPython 3.0.0-7-gcac760aa6 on 2018-08-20; Adafruit Feather M0 Express with samd21g18
>>> import test_uart
>>> test_uart.uart.write(b'\xbb')
1
>>> test_uart.uart.read(1)
b'\xbb'
>>> 
```

While testing this, please **actually power cycle** (don't just use the reset button) before uploading a fresh firmware.  It may be superstition on my part, but while originally debugging this problem I believe I had experiences where the 'bad' state that the buggy UART put the microcontroller into survived the soft-reset caused by the reset button.

**Comment by dhalbert** [comment]
@jepler Thanks for vetting. I think we can close.
