### ISSUE TITLE
Always allow variable frequency in PWMOut?

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#113]
I noticed PWM out has a concept of allowing frequency changes, but it has to be explicitly enabled with variable_frequency=True in the initializer.  Any reason to not just always default this to on for more flexibility?  Curious if there's any code or hardware impact.

**Comment by tannewt** [comment]
We could default it to on. When it is on it causes the underlying code to "claim" a whole timer rather than being willing to share. When the frequency is fixed multiple PWMOuts can share a timer for the same output frequency (like motors and servos). Its a trade-off between frequency flexibility and pin flexibility. Let me know if you still think its worth changing. Its really a matter of which case we think is more likely, flexible frequency or multiple outputs of the same frequency.

**Comment by tannewt** [comment]
I'm going to leave it as is. Please reopen if you disagree.
