### ISSUE TITLE
[feature request] Add direct memory access like machine.mem in Micropython

### ISSUE THREAD

**Issue by uhrheber** [adafruit/circuitpython#1268]
Please add a simple method for direct memory access to circuitpython.

Micropython has the machine.mem8/16/32 object, to access the memory directly.
Example: machine.mem32[0x50000748]=0x703

There are many situation where you want to access the memory, especially the registers, directly.
May it be speed, or because you need a special feature, that the driver/hal doesn't support.

It is possible to use @micropython.viper, and use pointers to access the memory, but I don't know what the status of the viper emitter is in circuitpython, and whether it will be supported in the future.

**Comment by tannewt** [comment]
The Adafruit sponsored development of CircuitPython is very beginner focused so myself or @dhalbert will not get to this anytime soon. I do agree that it'd be useful for advanced users. I'd be happy to help someone else implement this.

I think we'd actually want two different modules:
1. A `memory` module that gives direct access to RAM which is generic across all CircuitPython ports.
2. A `<port>_memory` module that gives access to the full memory space. Having this as a platform specific module will make it easy to recognize when python code is used on an incompatible platform. For example, if a driver uses the `nrf52_memory` module but is used on a samd21 then it will fail with an import error because it provides `samd21_memory` instead.

**Comment by siddacious** [comment]
With a _lot_ of guidance I might be able to work on this however I'm pretty busy at the moment. If someone else is interested by all means take it on.

**Comment by uhrheber** [comment]
I just received my DK. Give me some time to get used to it and wade through the circuitpython code.

@siddacious: I'd be happy to collaborate. 

@tannewt: Would it be OK to share our progress here, or should we set up a thread in the forum, or somewhere else?

**Comment by tannewt** [comment]
@uhrheber Here is great! Let me know if you have questions about CircuitPython code. Thanks!

**Comment by uhrheber** [comment]
You might have seen this: [#1248](https://github.com/adafruit/circuitpython/issues/1248#issuecomment-429667062)
Using @micropython.viper or @micropython.asm_thumb is already a usable way to access the memory and registers.

**Comment by dhalbert** [comment]
Superseded by #3234, but seeing how MicroPython does is worth looking at.
