### ISSUE TITLE
Long Term: port to risc v

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1438]
this board is the first embedded risc-v processor but porting would allow for flexibility in the future:
https://www.sifive.com/boards/hifive1

**Comment by tannewt** [comment]
The HiFive1 doesn't have native USB so I'd rather not port to it.

However, the FPGA folks will have native USB and RISCV cores. It brings up an interesting point though where we really define a port by peripheral family instead of the cpu core itself. Porting to the RISCV cpu itself shouldn't be hard since its a gcc change. The peripheral support is the hard part.

**Comment by TG-Techie** [comment]
thank you @tannewt  very helpful information about how porting is done as of now, and brain candy.
