### ISSUE TITLE
Create "code.py" when creating the filesystem

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#2149]
That way folks who install it have a file to edit. Bonus points if there is a very small bit of useful code. (Maybe just `print("Hello world!")`? It could be the translation too.)

**Comment by iayanpahwa** [comment]
I think it would be really great to have a code.py file considering the fact that recommended mu editor looks for that file and automatically loads in on detecting a CP board. A small demo code to print hello world or LED blink will also be great to have. @tannewt can I work on this one ?

**Comment by jepler** [comment]
@iayanpahwa Please feel free to work on this and file a pull request.

In case you didn't learn this yet for yourself, the area of the code to work in is probably `supervisor/shared/filesystem.c` between
```
        // No filesystem so create a fresh one, or reformat has been requested.
        uint8_t working_buf[_MAX_SS];
        res = f_mkfs(&vfs_fat->fatfs, FM_FAT, 0, working_buf, sizeof(working_buf));
```
and
```
        // and ensure everything is flushed
        supervisor_flash_flush();
```

**Comment by iayanpahwa** [comment]
@jepler Thank you for code reference. I'll star working on it :)

**Comment by iayanpahwa** [comment]
@tannewt @jepler should we do code.py have 

* print ('Hello World!') or
* Blink BUILT_IN LED program

**Comment by jepler** [comment]
@iayanpahwa let's start with "Hello World".  It can be changed to a more sophisticated example later on, if that's what's desired.

**Comment by deshipu** [comment]
I would also love to be able to disable this on per-board basis, to save space for the smaller boards.

**Comment by jepler** [comment]
@deshipu I agree.  @iayanpahwa after you have the basics working, let us know if you need guidance on how to make the code optional

**Comment by iayanpahwa** [comment]
@deshipu sounds cool. @jepler thinking a makefile flag?

**Comment by jepler** [comment]
@iayanpahwa yes something that can be controlled from a `mpconfigboard.mk` file would be the ideal result.  Ideally you would make the default be `$(CIRCUITPY_FULL_BUILD)` so that it is automatically excluded on chips with less program space available.

You may find it useful to study how e.g., CIRCUITPY_DISPLAYIO works.  Files involved include individual `mpconfigboard.mk` files, `py/circuitpy_mpconfig.mk` to set a default value, and `supervisor/shared/display.c` to make a decision based on whether CIRCUITPY_DISPLAYIO is enabled or not.

Let us know how it goes!

**Comment by iayanpahwa** [comment]
PR created - #2298

**Comment by iayanpahwa** [comment]
PR Created - #2299

**Comment by iayanpahwa** [comment]
PR #2299 merged. This issue can now be closed.

**Comment by jepler** [comment]
Thanks @iayanpahwa !
