### ISSUE TITLE
displayio broken for CLUE, others?

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#2750]
Updated repo to latest (78c1448) and did a build for CLUE. Could connect to REPL but nothing on TFT. Went backwards in commits and found:

- `b043384` works
- `54e8c63` does not work

So maybe something with #2730 ?

**Comment by tannewt** [comment]
Turns out it was something I missed in #2733. It appeared an issue between b043384 and 54e8c63 because b04 was based on the state of master before #2733 was merged. The commit list is deceiving because git history isn't linear. The changes between b04 and master are only in master with the merge commit 54e.

A way to get around this is to only test merge commits when finding the bad commit.

Fix is in PR #2753
