### ISSUE TITLE
Rotary encoder support

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#283]
SAMD51 has a peripheral for it.

**Comment by sommersoft** [comment]
Just wanted to make some notes here. I was skimming through Noridc documentation, and noticed that nRF52x also has rotary encoder as a peripheral. Not surprising, since it's M4 based. 

They refer to it as "Quadrature decoder" or "QDEC". Here are links to the documentation:
- nRF52832: [QDEC](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52832.ps.v1.1/qdec.html?cp=2_1_0_35#concept_isq_pwd_4r)

- nRF52840: [QDEC](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52840.ps/qdec.html?cp=2_0_0_34#concept_isq_pwd_4r)

**Comment by microbuilder** [comment]
The Arduino nRF52 Repo contains a [RotaryEncoder](https://github.com/adafruit/Adafruit_nRF52_Arduino/tree/master/libraries/RotaryEncoder) library with both HW and SW implementations for this, just as a reference. If a common API is added at the HAL layer, it shouldn't be too complicated to add nRF52 support used the QDEC peripheral or GPIO.

**Comment by ladyada** [comment]
making a note here that SAMD has very fixed pins for QDEC - so for that platform, at least, we should just DIY with a timer interrupt - an existing one would probably be fine as the checking code is very small

**Comment by tannewt** [comment]
Anyone mind if I punt this to 4.0?
