### ISSUE TITLE
ReadTheDocs PDF build fails

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#3261]
As reported here: https://forums.adafruit.com/viewtopic.php?f=60&t=168181

**Comment by sommersoft** [comment]
I started looking into this a couple days ago.

It looks like it could be as simple as adding the [`formats`](https://docs.readthedocs.io/en/stable/config-file/v2.html#formats) directive to `.readthedocs.yml`.

However, Sphinx is refusing to build with LaTeX since the Jinja doesn't get parsed in `shared-bindings/support_matrix.rst`. The HTML version processes the Jinja via `docs/rstjinja.py`, so I'm trying to debug my way through adding the LaTeX version to do the same.
