### ISSUE TITLE
ESP32-S2: 2nd USB-serial channel wanted

### ISSUE THREAD

**Issue by emard** [adafruit/circuitpython#3327]
It would be great to have secondary USB-serial channel
for bidirectional interface to external RX/TX pins
(possibly also other control lines RTS CTS etc if techology allows)

This would replace need of additional USB-serial cable.

**Comment by tannewt** [comment]
Hi! We would like to add a second CDC interface to our USB descriptor but it requires dynamically changing the descriptor because of the limited endpoints. We have an existing issue for this here: https://github.com/adafruit/circuitpython/issues/231 It also has a lot of background related to what you are trying to do.
