### ISSUE TITLE
digitalio 'Pull.DOWN' is not working on CLUE board

### ISSUE THREAD

**Issue by aoyamaprod** [adafruit/circuitpython#3350]
On Adafruit CLUE board and CircuitPython 5.3.1

I tried the following code on my CLUE board and works fine.
When Button A 'not' pressed, it returns True and when Button A is pressed, it returns False. This is okay.

`
import time
import board
from digitalio import DigitalInOut, Direction, Pull

button_a = DigitalInOut(board.BUTTON_A)
button_a.direction = Direction.INPUT
button_a.pull = Pull.UP

while True:
    print (button_a.value)
    time.sleep(0.1)
`

When I changed the code Pull.UP to Pull.DOWN as below, it returns only False even I pressed the Button A.
Is it from some issue? or did I miss something?
`
import time
import board
from digitalio import DigitalInOut, Direction, Pull

button_a = DigitalInOut(board.BUTTON_A)
button_a.direction = Direction.INPUT
button_a.pull = Pull.DOWN

while True:
    print (button_a.value)
    time.sleep(0.1)
`

**Comment by jerryneedell** [comment]
This is to be expected. If you look at the schematic https://cdn-learn.adafruit.com/assets/assets/000/087/877/original/adafruit_products__CLUE_sch.png?1580423083  the buttons are connected on one side to Ground and the other side to the GPIO Pin. Pressing the button connects the Pin to Ground so it will read False.
When you us the Pull-Up/Down setting , you are setting the "default" state of the GPIO Pin when nothing is connected to it (when the Button is not pressed)
When you use a Pull-UP the GPIO pin will read True unless the Button is pressed to connect it to Ground so it reads False.  If you use a Pull-DOWN the Pin will read False all the time since pressing the button does not change anything.
