### ISSUE TITLE
double file extensions

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#383]
![image](https://user-images.githubusercontent.com/1214161/32137053-d4379cd0-bbe6-11e7-8e59-345ad4b34f95.png)

might be worth detecting this kinda thing at the 'end' of the list of files we run - windows tries to be 'smart' and not show extensions!

**Comment by siddacious** [comment]
Do you mean we should run double extension files at a lower priority or just give a warning about them?

**Comment by ladyada** [comment]
probably just run them at a lower priority - but a warning on REPL-open might be good

**Comment by ladyada** [comment]
@siddacious if you're interested in taking this on, you can start by adding the list of files and we can do the warning later :)

**Comment by siddacious** [comment]
Do we care about all the possible combinations or just doubling of the same extension?

**Comment by dhalbert** [comment]
It would probably be good to make up a table of possibilities or iterate through the combinations, instead of having multiple calls to `maybe_run()`.

**Comment by siddacious** [comment]
I've got the simple version but I'll take a whack at the warnings and combo iteration when I get home.

**Comment by siddacious** [comment]
So I'm *so close* to being done with this except for the part where it's totally broken. When I take one of the generated double extension file names and run it (blinky in this case) with `pyexec_file(double_extension_filename, exec_result);` I see my led blink but I loose the CDC serial in /dev/tty* and CIRCUITPY doesn't show up. I assume it's running the blinky that I had previously uploaded and tested with master (5ff6) successfully since I don't have MSC to upload a new file with.

I'm going to try poking at it a bit but if I can't figure it out I'll commit to my fork so someone can point out what I'm doing wrong.

**Comment by tannewt** [comment]
Is your branch based on 5ff6 as well? I'd be happy to take a look tomorrow.

**Comment by siddacious** [comment]
I found the bug; I had not noticed that the two calls to `maybe_run` had different arguments and treated them as the same. I simplified how it works and addressed that oversight in doing so. Now I'm just trying to remember how to pointer.
