### ISSUE TITLE
Revamp status LED signaling

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#4133]
@tannewt discussed revisiting the multi-colored status LED blinking that CIrcuitPython does to indicate errors. I think the ideas were to:
- simplify the indications
- do not repeat them indefinitely

@tannewt Please revise this post or comment as necessary.

**Comment by tannewt** [comment]
Yup! I think we only want to use the status LED on power up (not every reset) and on error. The main goal is to save power.

**Comment by Dygear** [comment]
Watching the live stream from [this week's deep dive](https://youtu.be/Q4sUzNMQA0U?t=4871) and thinking about colors. I was thinking something like ...

- Red for Compile Time Errors (Blink Morse Code "SOS" x2)
- Yellow for user land thrown and uncaught Exceptions. (Blink Morse Code "Error" x2)
- Purple for when it's first running the code. (Blink Morse Code "Run")
- Green for when it gets to code completion. (Blink Morse Code "Done").

SOS = `... --- ...`
Error = `. .-. .-. --- .-.`
Run = `.-. ..- -.`
Done = `-.. --- -. .`
Help = `.... . .-.. .--.`

So why the color and then morse code? Some people are color blind, this allows them to get some information from this LED as well. I am not color blind myself, but designing UI / UX for governmental type organizations, these types of things are a requirement due to the [ADA](https://www.dol.gov/general/topic/disability/ada) -- As well as ya know just being nice.

**Comment by tannewt** [comment]
> [Edit] Oh, and like a minute after I paused to write this you said you didn't want morse code and you're going into much more detail about what you have planned. I would really wait until the end of the video before I make comments. LOL. Sorry.

No worries! Thanks for the thinking on this.

**Comment by hierophect** [comment]
This is kind of a trivial note but how will this activate with regards to deep sleep? Currently, while waiting for USB to enumerate, Deep Sleep iterates constantly over the `tick_rgb_status_animation` call in main. There is also the general difference between true and fake deep sleep in terms of how they trigger a restart, and the fact that chips like the RP2040 which do not reset their own flash may always use the fake deep sleep method. I have no real preference on the actual specifics of these points, just bringing them up in case you feel any of them might be important.

**Comment by tannewt** [comment]
My plan is to get rid of the tick function and make the loop in main more like the time.sleep loop. So, between changing flashes it would light sleep.
