### ISSUE TITLE
samd51 200mhz support

### ISSUE THREAD

**Issue by kahveciderin** [adafruit/circuitpython#4176]
Any support for this? maybe making the ```microcontroller.cpu.frequency``` settable would help

**Comment by tannewt** [comment]
We've discussed this a bit but it's not easy to do well. Changing clocks tend to have cascading impacts on peripherals as well. Leaving open because I imagine we'll do it at some point.

An intermediate version would allow changing it in `boot.py` once. I think folks may want full support though for power saving too.

**Comment by hierophect** [comment]
Superseded by #4339, to generalize across ports.
