### ISSUE TITLE
Add smartconfig capability for esp8266

### ISSUE THREAD

**Issue by zaforic** [adafruit/circuitpython#428]
Add smartconfig capability to micropython for esp8266

Create smartconfig python wrapper. An old example is at https://github.com/mianos/micropython/blob/master/esp8266/mod_esp_smartconfig.c

Add the following:
{ MP_ROM_QSTR(MP_QSTR_smartconfig), MP_ROM_PTR(&mp_module_esp_smartconfig) },

**Comment by ladyada** [comment]
hiya just to update, we won't be supporting the ESP8266 long term, due to the lack of USB and low RAM availability. instead, we'll be using it as a co-processor to bigger chips! check this guide for more details
https://learn.adafruit.com/adding-a-wifi-co-processor-to-circuitpython-esp8266-esp32
thank you :)
