### ISSUE TITLE
Circuitpython canio module on STM32F407 and STM32F412 boards

### ISSUE THREAD

**Issue by Shubhankargo** [adafruit/circuitpython#4382]
Hi

I'm new to Circuitpython. I am trying to build a CAN bus based application on circuit python. Can anyone tell me if the canio module is available on the on STM32F407 and STM32F412 discovery boards? Or will I have to purchase a STM32F405 feather board from Adafruit?

Thanks.

**Comment by hierophect** [comment]
@Shubhankargo, both of those chips have CAN peripherals and _should_ work with our current module, but we don't seem to have them enabled. @jepler can we turn this on for all F4 chips, or at least for the F407? The F407 should definitely work, the F412 should _probably_ work, but it could have some weird register differences as an "access" level F4 chip.

**Comment by jepler** [comment]
You can check the list of supported modules on the circuitpython.org downloads page for the specific board, such as https://circuitpython.org/board/stm32f4_discovery/.  The canio module is not available at this time for "STM32F407 Discovery kit" or "STM32F412 Discovery kit".  We would be happy to accept a pull request to enable it, if it is supported by the underlying hardware.

**Comment by Shubhankargo** [comment]
Thank you for your response guys.

The download pages of neither of those boards (chips) show the 'canio' module as enabled. Are you saying that I can add the bin file for the STM32F07 and run the module like normal?

Sorry I'm a bit of a noob and not too well versed with pull requests.

**Comment by microDev1** [comment]
@Shubhankargo The module list will be update once a new release is published.
For now you can test the latest build by grabbing it from [S3](https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/).

**Comment by hierophect** [comment]
@Shubhankargo note that I did not add the F412, it's not a direct superset of the F405 like the F407 is and I don't have the cycles to test it right now.

**Comment by Shubhankargo** [comment]
Thanks for the help guys.
So since the STM32F07 is a strict super set of the STM32F05, should load the circuitpython .bin file of the STM32F05 Feather directly into the F07 Discovery board, or just copy the canio module into the lib after loading the STM32F07 .bin file?

**Comment by hierophect** [comment]
@Shubhankargo I'm not sure I understand what you mean. You should not use the Feather binary since it will have totally different pin definitions and oscillator settings. CanIO is a native module and does not have a .mpy file in the libraries folder of the filesystem, so I'm not sure what you mean there either.

If you want to use CAN on the F407 Discovery now that support has been merged, you should visit the [s3](https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/) link and click through the `stm32f4_discovery/` to get the latest build in your preferred language, or the [build artifacts for the PR](https://github.com/adafruit/circuitpython/pull/4385/checks) for a zip file of builds from that specific commit for the F4 discovery.

**Comment by Shubhankargo** [comment]
Apologies for not getting back earlier on this. The solution worked perfectly. Thank you @hierophect .
