### ISSUE TITLE
PIO: add support for the "jmp pin"

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4413]
The PIO module can support a conditional jump based on a GPIO pin.  However, the pin to use can't be specified in CircuitPython. Let's add it!

**Comment by daveythacher** [comment]
Related files:
https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/bindings/rp2pio/StateMachine.c
https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/common-hal/rp2pio/StateMachine.c

**Comment by NathanY3G** [comment]
Hi. If there are no objections I would like to take this issue on!

**Comment by jepler** [comment]
@NathanY3G thank you for offering! I've assigned the issue to you. Let us know how we can help you get up to speed working on the CircuitPython core—our [Discord](https://adafru.it/discord) is a great place to find help as well, just drop in to #circuitpython-dev and ask a question.

**Comment by NathanY3G** [comment]
Cheers Jeff :-)

**Comment by dmcomm** [comment]
Looking forward to it :)

**Comment by NathanY3G** [comment]
I have created a pull-request and would be grateful for some feedback, especially since this is my first contribution to CircuitPython: https://github.com/adafruit/circuitpython/pull/5042

Testing: this change was manually tested on a Feather RP2040 and a RPi Pico by using the attached test.

[jmp_pin_interactive_test.txt](https://github.com/adafruit/circuitpython/files/6867232/jmp_pin_interactive_test.txt)
