### ISSUE TITLE
Finish PWM on mimxrt1011

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4541]
Basic PWM has been enabled, but there are still limitations.  Here are the ones I know of:
- [x] never-reset PWMs (like for backlight)
- [x] correct checking for PWM sharing
- [x] support for "X-channel" PWM, if possible (no code in SDK for it) - this affects only pin A4 (and ESP_READY) on the metro m7 1011

**Comment by tannewt** [comment]
I don't think I'll add X channel support because it'll limit frequencies to the prescaler capable ones. VAL1 is used for top value usually but then it leads to a low pulse every cycle on X. This would prevent 100% duty cycle.

![image](https://user-images.githubusercontent.com/52649/219219682-5837ea97-001d-4b40-95e3-01a49eec5955.png)

**Comment by tannewt** [comment]
Nevermind, I added X support but it'll raise an error on 100% duty cycle. Note, it also has a fixed falling edge when most PWM are fixed leading edge. The CircuitPython API doesn't explicitly say which it is.
