### ISSUE TITLE
Add built-in neopixel library

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#56]
So that they can't delete it off the file system.

**Comment by tannewt** [comment]
We should do this as a submodule with a script to autoupdate similar to the bundle. We should also prefer filesystem copies to built in versions in case there are bug fixes.

**Comment by ladyada** [comment]
maybe only built in on cplay express? im ok with that!

**Comment by tannewt** [comment]
I was thinking all of the Express boards since they have the room.

**Comment by dhalbert** [comment]
Add as a git submodule and build in as an internal frozen module? Disadvantage is you need a new CPy release to update. Advantage is built-in, can't be deleted, and no RAM used for the code when you import. You could add more convenience functions without worrying about RAM usage.

**Comment by tannewt** [comment]
Yeah, that was my plan. We can get around the upgrade disadvantage by preferring modules from the filesystem first.

**Comment by tannewt** [comment]
Note that frozen modules are currently loaded when the path is "". I think we should change it to something like ".frozen" to be explicit. We'll need to change the make-frozen.py script to change the filenames.

**Comment by dhalbert** [comment]
Working on branch https://github.com/adafruit/circuitpython/tree/issue_56_frozen_neopix_lib; checked in snapshot.

Modules to freeze will be added as git submodules to the `frozen/` directory. I modified the makefiles to allow multiple directories to freeze: `FROZEN_MPY_DIRS` instead of singular `FROZEN_MPY_DIR`. Frozen modules to include for a specified board are specified in `mpconfigboard.mk` files. Rewrote frozen code generation rules in `py/mkrules.mk`; I think it's more straightforward now. There's still the peculiar `$(BUILD)/$(BUILD)/frozen_mpy.o` path in `py/py.mk`. I haven't gotten rid of this successfully.

Tested on CPX: only one neopixel is working. Not sure if that's a library issue or a frozen module issue.
