### ISSUE TITLE
Bitmap.blit from OnDiskBitmap => hard crash

### ISSUE THREAD

**Issue by rsbohn** [adafruit/circuitpython#5916]
### CircuitPython version

```python
Adafruit CircuitPython 7.1.0 on 2021-12-28; Adafruit FunHouse with ESP32S2
```

### Code/REPL

```python
import displayio
with open("/bmp/allblue.bmp","rb") as bits:
    source = displayio.OnDiskBitmap(bits)
    dest = displayio.Bitmap(source.width, source.height, 64)

dest.blit(0,0, source)
```

### Behavior

Hard reset of FunHouse board.

### Additional information

May not be possible, but the response should be an error message rather than a hard crash.

**Comment by rsbohn** [comment]
[allblue.zip](https://github.com/adafruit/circuitpython/files/7928123/allblue.zip)
Here is the bitmap used in the script.

**Comment by FoamyGuy** [comment]
I think bitmaptools.blit() is expecting to operate on a "normal" `Bitmap` object rather than an `OnDiskBitmap`.

If you are using it with a bmp file I think the file needs to be loaded with `adafruit_imageload`

We should definitely have a better error mitigation and avoid the hard crash though.

**Comment by jepler** [comment]
It looks like `Bitmap.blit` intends to only accept another `Bitmap` but has insufficient error checking. We should fix this bug so that a TypeError exception is raised.

Also, while it may have been suggested by a linter, this is not correct usage:
```python
with open("/bmp/allblue.bmp","rb") as bits:
    source = displayio.OnDiskBitmap(bits)
```
because the OnDiskBitmap object needs to retain an open file for its whole lifetime, this won't work properly. Instead, the `source` bitmap becomes unusable at the end of the `with` statement. You'd instead just want to write:
```python
source = displayio.OnDiskBitmap(open(...))
```
or separate it into two lines, as the documentation suggests:
```python
odb = displayio.OnDiskBitmap('/sample.bmp')
face = displayio.TileGrid(odb, pixel_shader=odb.pixel_shader)
```

**Comment by rsbohn** [comment]
I should have put the `.blit()` inside the `with` form. For normal usage you are correct, but if I can copy the bits to a second bitmap the original file is no longer needed.

**Comment by rsbohn** [comment]
Thanks for working on this issue.
