### ISSUE TITLE
UART connection between two KB2040 boards fails

### ISSUE THREAD

**Issue by alecharp** [adafruit/circuitpython#5953]
### CircuitPython version

```python
Adafruit CircuitPython 7.1.1 on 2022-01-14; Adafruit KB2040 with rp2040
```

### Code/REPL

```python
import board, busio
busio.UART(tx=board.RX, rx=None)
```

### Behavior

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid pins
```

### Description

On a Sofle keyboard, with KB2040, the two D1 pins of the boards are connected through a TRRS connector (and cable). However, the connection cannot be made.
Trying to create a UART object fails, with or without the two half connected.

Is D1 only for reception and cannot be used as the transmitting pin? Do this means that the crossing of the Rx/Tx connections have to be done on the hardware and cannot be made on the software?

**Comment by tannewt** [comment]
> Is D1 only for reception and cannot be used as the transmitting pin? Do this means that the crossing of the Rx/Tx connections have to be done on the hardware and cannot be made on the software?

With `busio.UART()` yes because it uses the UART peripherals of the RP2040. However, you can use pio to do either UART TX or RX.

For TX, ensure you have the absolute newest version of CircuitPython. I recently added support for a PIO feature used by UART TX. There classes that present the same API as `busio.UART` in the PIO examples. https://github.com/adafruit/Adafruit_CircuitPython_PIOASM/blob/main/examples/txuart.py

Ideally the Sofle would allow for crossing the pins using a jumper. As-is, they are arranged for I2C instead of UART.
