### ISSUE TITLE
Metro M4 Express unable to save once boot.py is loaded

### ISSUE THREAD

**Issue by phantomsixthplayer** [adafruit/circuitpython#6130]
### CircuitPython version

```python
adafruit-circuitpython-metro_m4_express-en_US-7.2.0
update-bootloader-metro_m4-v3.14.0
```

### Code/REPL

```python
boot.py:
import board
import digitalio
import storage

# Metro M4 Express
switch = digitalio.DigitalInOut(board.D13)
switch.direction = digitalio.Direction.INPUT
switch.pull = digitalio.Pull.UP

# If the switch pin is connected to ground CircuitPython can write to the drive
storage.remount("/", switch.value)

code.py:
print("Hello World!")
```

### Behavior

Mu:
Could not save file (disk problem)
Error saving file to disk. Ensure you have permission to write the file and sufficient disk space.

### Description

The drive is empty beside default files, once I place the boot.py file on the drive I cannot edit any files on the drive again. The switch pin wire is not connected to GND, only way around is to [Erase CIRCUITPY Without Access to the REPL](https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting)

### Additional information

[CircuitPython Storage](https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage)

**Comment by dhalbert** [comment]
Pin D13 is connected to the red LED through a resistor, which is going to try to pull the signal to ground all the time. Pick a different pin that has no other connection.

You can get into safe mode by pressing the reset button when the NeoPixel is yellow. This is hard to do because of human reaction time, but a "slow" double-click reset can usually hit it. See https://learn.adafruit.com/welcome-to-circuitpython?view=all#circuitpython-7-dot-0-0-and-later-2978455-21.
