### ISSUE TITLE
pimoroni servo 2040: board.NEOPIXEL

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6307]
The board module has `LED_DATA` but it should probably be using the standard name `NEOPIXEL`.

**Comment by ladyada** [comment]
@ZodiusInfuser

**Comment by ZodiusInfuser** [comment]
If `board.NEOPIXEL` is the convention, and the appropriate name for multiple LEDs (rather than `board.NEOPIXELS`), then this sounds fine to change. I went with LED_DATA because it's more generic and matches the pin name on the schematic. This by extension means our C++, MicroPython, and CircuitPython board definitions are consistent.

Let me know whichever way, as we'll have other board hopefully launching this week with a similar setup that I'm yet to raise the PR for.

**Comment by ladyada** [comment]
@ZodiusInfuser you can add an alias for NEOPIXEL - please submit a PR :)

**Comment by jepler** [comment]
CircuitPlayground (Express & Bluefruit), PyGamer, and PyBadge at least have multiple neopixels attached to board.NEOPIXEL, that's not a problem.
