### ISSUE TITLE
Xiao/Qt-py filter for downloads

### ISSUE THREAD

**Issue by alustig3** [adafruit/circuitpython#6371]
A Xiao/QTPy checkbox under the filter->features section of the  https://circuitpython.org/downloads?sort-by=downloads would be useful.

**Comment by alustig3** [comment]
also, the text for **"Wi-Fi (Two Version Onboard Antenna Or UFL Connector)"** seems to have been split across two checkboxes
![split feature title](https://user-images.githubusercontent.com/8128628/167507660-3ff00e03-64bc-462e-8c1d-551cdda1446d.png)

**Comment by jepler** [comment]
Thanks for the suggestion. I've fixed the second problem you noted, and offered a pull request to add the new 'feature', though I don't know whether Adafruit will choose to accept it.

If you have further issues or enhancements specifically about the circuitpython.org website, you can file them over on that repo: https://github.com/adafruit/circuitpython-org/ -- though it's no trouble that you filed this issue here.

Thanks again!

**Comment by alustig3** [comment]
Thanks a lot!

**Comment by jepler** [comment]
Thanks again for the suggestion.
