### ISSUE TITLE
Filesystem isn't allowing me to write to it

### ISSUE THREAD

**Issue by pianpie** [adafruit/circuitpython#6716]
My filesystem isn't allowing me to write to it. I imported storage correctly but the filesystem is stuck in in read-only for circuit python. I followed [this](https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage) guide and it didn't work. The filesystems mode was never changed. I am using the metro m4 express.
Boot.py:

```
import board
import digitalio
import storage



# For Feather M0/M4 Express
switch = digitalio.DigitalInOut(board.D2)

switch.direction = digitalio.Direction.INPUT
switch.pull = digitalio.Pull.UPswitch.direction = digitalio.Direction.INPUT
switch.pull = digitalio.Pull.UP
# If the switch pin is connected to ground CircuitPython can write to the drive
storage.remount("/", switch.value)
```
code.py:

```
import time
import board
import digitalio
import microcontroller
import storage
led.switch_to_output()
switch = digitalio.DigitalInOut(board.D2)
switch.direction = digitalio.Direction.INPUT
switch.pull = digitalio.Pull.UP
print(switch.value)
try:
    print("in try")
    with open("test.txt", "a") as fp:
        while True:
            fp.write("this works")
            led.value = not led.value
            print("pog")
            time.sleep(1)
except OSError as e:
    print("os error")

    while True:
        time.sleep(1)
        print(switch.value)
```
The filesystem isn't being changed and it's stuck in read-only for circuit python

**Comment by RetiredWizard** [comment]
You have some switch logic in your code.py. The read/write status of the Circuit Python Flash is determined when boot.py is run only, so any changes to the switch value in code.py will have no impact on the flash.

It looks like your boot.py should correctly set the read/write status when the Metro M4 is powered up. In order to set the flash so Circuit Python can write to it, you need to jumper D2 to ground and then power up or press the reset button on the Metro. A control-D reset will **NOT** run the boot.py or change the read/write status of the flash.

Have you tried testing the functionality by hardcoding the switch value in boot.py?

i.e. `storage.remount("/", False)`
