### ISSUE TITLE
Reclaim OTA1 for CIRCUITPY

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#6928]
The problem
-----------

ESP32 boards have two partitions OTA0 and OTA1 to allow the use of the dualbank module, to flash a new firmware while running and switch. On 4MB boards for example where CP takes 1.5MB and only ~950kB are left to the drive, the OTA1 partition is actually bigger than the drive itself.

- This doubles the space taken by CP, at the cost of the CIRCUITPY drive.
- The `dualbank` module is likely **almost** never used by anyone.
- New users can be puzzled (and disappointed) by that amount of "wasted" space.

See: https://github.com/adafruit/tinyuf2/issues/227

How to reclaim that lost space ?

It is possible to change the partition scheme, To remove OTA1 and make the fat partition use the reset of the space. That would require manually compiling or doubling the number of builds. And I'm not sure how complicated it would then be to make Circuitpython dynamically detect which partition size and location to use. I believe the partition scheme is currently fixed on build.

Changing the partition scheme could also break compatibility between versions, not to mention make it quite complicated to switch between the 2 modes, to either extend the drive or enable `dualbank`.

Proposal
--------

Keep the current partition scheme, but make Circuitpython optionally (or by default) use the OTA1 partition to extend the file system.

- It would be a mode that can be switched with an option to `erase_filesystem()`, since the drive would have to be erased anyway.
- I believe that tinyuf2 never writes to ota1 (at least CP) so updating CP would not corrupt the drive. Am I right ?
- The ota1 and fat partitions are not contiguous, so it would require the drive code (the filesystems and tinyusb MSC) to support having blocks in multiple flash sections (some form of address translation?)
- The `dualbank` module would return an informative error when in extended drive mode.
- The partition scheme could be changed to move OTA1 next to the fat partition, though I believe that would requite an update to tinyuf2, which makes it more complicated than just updating CP.

**Comment by MicroDev1** [comment]
As @Neradoc suggests, following are the two approaches for extending `CIRCUITPY`:
1. **Static Approach:** Turn off `dualbank`, remove `ota_1` partition and extend `user_fs` partition during build.
This is addressed in #6927.
2. **Dynamic Approach:** Add API to turn off `dualbank`, combine `user_fs` and `ota_1` at runtime.

I believe we need both, the static approach can be for boards which have a large overflow and require either turning off multiple modules or just dualbank, latter looks like the more preferred option. All other boards can go with the dynamic approach.

I did a test implementation of the dynamic approach locally and it seems to work fine. 🚀

> ...a mode that can be switched with an option to erase_filesystem(), since the drive would have to be erased anyway.

It would be ideal to have the ability of extending partition size without erasing it, when reducing the partition size we can first check if the used space is more than the targeted space.

> I believe that tinyuf2 never writes to ota1 (at least CP) so updating CP would not corrupt the drive. Am I right?

Yes, TinyUF2 doesn't write to `ota_1` so that isn't a problem.

> The ota1 and fat partitions are not contiguous, so it would require the drive code...

I don't think it matters whether the partitions are contiguous or not. In my local implementation, I am emulating a single partition to read/write by conditionally selecting the partition depending on the offset and size.

**Comment by MicroDev1** [comment]
I unstreamed my local changes:
- The crude implementation is [here](https://github.com/MicroDev1/circuitpython/commit/29b148ebf0ceeb28442112d0c2260818fa748395).
- Build Artifacts can be found [here](https://github.com/MicroDev1/circuitpython/actions/runs/3114657721).
```py
import storage
storage.enable_extended()
storage.erase_filesystem()
```

**Comment by MicroDev1** [comment]
I upstreamed my local changes:
- The crude implementation is [here](https://github.com/MicroDev1/circuitpython/commit/29b148ebf0ceeb28442112d0c2260818fa748395).
- Build Artifacts can be found [here](https://github.com/MicroDev1/circuitpython/actions/runs/3114657721).
```py
import storage
storage.enable_extended()
storage.erase_filesystem()
```

**Comment by UnexpectedMaker** [comment]
I think the dynamic approach is a great solution - as it's something users can just do (be pointed to when they query the limited about of flash available), rather than depending on the build system to make multiple versions.

Thanks for jumping on this @MicroDev1 :)

**Comment by bill88t** [comment]
@MicroDev1 
> I upstreamed my local changes

I am not quite sure on how to stress test this..
Do you want me to expand, fill the storage and then md5 all the files?

**Comment by bill88t** [comment]
The `Dualbank` is effectively **undocumented**.

Do I take the .bin?
Does it work with tinyuf2?
How am I meant to know the offsets?

Assuming it's functionallity is as written in the docs, it seems pointless to have the partitions "split" by default.
From my point of view, it would be best if the dynamic system was implemented, but "expanded" being the default.
99% of users will prefer the lots of storage instead of the bank switching.

**Comment by bill88t** [comment]
> Build Artifacts can be found here.

Testing the artifact on waveshare_esp32s2_pico.

After a nice swift backup of the current ljinux installation, I ran the commands specified.
After CIRCUITPY came back up, I restored the ljinux installation and powercycled the board.

First 500kb wget:
![image](https://user-images.githubusercontent.com/21365918/192100810-acbcb0ab-ea93-43b2-8495-579741722b21.png)

Matches with my Pi400:
![image](https://user-images.githubusercontent.com/21365918/192099070-a14a3237-e7a8-4a30-ba34-044b87334e7d.png)

It's still in the first partition.

Second 500kb wget:
![image](https://user-images.githubusercontent.com/21365918/192100971-e4202a6a-70b1-4af2-95e6-c0a8ccce61ab.png)

Absolute bananas.

From here on out, even if I `rm` it to free space, unless I `reboot`, all writes will be bananas.
And i'm not talking about wgets.. I open nano, type "amogus" for the sussy fs, save, and cat the file:
![image](https://user-images.githubusercontent.com/21365918/192101111-f511ca9a-1661-46f8-8dcd-cd5fed837884.png)

**Comment by bill88t** [comment]
The newer build doesn't work with psram so I cannot test.
esp32s2 has basically no ram without psram.
I may try on c3 in the next few days.

**Comment by MicroDev1** [comment]
@bill88t Thanks for starting to test this, it is still very much a work in progress, I'll make PR soon with a more stable version.

After some more tinkering with this, I'd like to propose that instead of only using `ota_1` to extend the storage, we should use the next update partition which could be either `ota_0` or `ota_1` depending on the current running partition.

This would allow storage extension to work with `dualbank`. When updating the firmware, an error can be raised if the `ota_x` partition contains user data. Also, storage extension can be turned off when both partition need to contain bootable firmware.

For this to work, TinyUF2 will have to be updated to flash the current running partition instead of defaulting to `ota_0`.
@hathach Your thoughts regarding the above.

**Comment by MicroDev1** [comment]
Any suggestions regarding the api, possible scenarios:
1. Internally extended by default and `erase_filesystem(extended: Optional[bool] = False)`
    - Issue: Mismatch between the internal default state and api default state. A fresh firmware will start with storage extended but calling `erase_filesystem()` with its default state will reduce it.
2. Internally extended by default and `erase_filesystem(extended: Optional[bool] = True)`
    - Issue: A user utilizing `dualbank.switch(both_bootable=True)` just calls `erase_filesystem()` and ends up with the other firmware wiped clean.
3. Internally **not** extended by default and `erase_filesystem(extended: Optional[bool] = False)`
    - Issue: Storage extension will likely end up getting unnoticed. Specially since `erase_filesystem()` is documented as a recovery function and fresh firmware won't start with storage extended.
4. Internally **not** extended by default and `erase_filesystem(extended: Optional[bool] = True)`
    - Issue: This has all of the above flaws.

Note: `extended` can't be made a required ARG as that would make it incompatible with other boards.

**Comment by bill88t** [comment]
On 2, a check could be in place if the other partition is a valid firmware, require `erase_filesystem(extended=True, force=True)`

1 will make the users think its a bug
