### ISSUE TITLE
document make version requrement (or figure out that's not right)

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7117]
I was working with Kattni, who eventually ran into trouble building CircuitPython:
```
make BOARD=raspberry_pi_pico
...
../../py/qstr.h:42:14: fatal error: genhdr/qstrdefs.enum.h: No such file or directory
   42 |     #include "genhdr/qstrdefs.enum.h"
```

We eventually established that:
 * she's on a mac, so `make --version` is 3.81
 * `brew install make` got her `gmake --version` of 4.3. Then, using `gmake BOARD=...` worked across 3 full builds
 * I built 3.81 on my linux box, and reproduced the problem there: `make-3.81 BOARD=raspberry_pi_pico_w -j1 build-raspberry_pi_pico_w/autogen_display_resources-en_US.o `
 * But I confirmed that with make 4.3 (default installed on my system) works consistently

I think we should document that (A) make 3.81 is too old (B) make 4.3 is recommended and tested and (C) that it can be installed on macs with `brew install make`, then referred to as `gmake` in commands.  The `gmake` name can be used on Linux systems and probably cygwin/windows systems too.

It may still be the case that it's a bug in our Makefiles but if it consistently works just by installing an up to date make rather than a 16 year old one, I don't want to spend a lot more time on it.

**Comment by dhalbert** [comment]
I revised the Building CircuitPython Learn Guide to include the information above. I actually had more trouble than what was described above: I have Ventura 13.0 installed, along with the latest Xcode. `make --version` asks me to install the Xcode command line tools. I did that twice, and even logged out, and it keeps asking me. So that's yet another problem.
