### ISSUE TITLE
time.sleep "soft reboot" on ESP32S2-S2FN4R2

### ISSUE THREAD

**Issue by davidr99** [adafruit/circuitpython#7155]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.3 on 2022-10-20; S2Mini with ESP32S2-S2FN4R2
```

### Code/REPL

```python
import time
while True:
    print("Sleeping!")
    time.sleep(1)
    print("Loopping!")
```

### Behavior

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;🐍192.168.1.138 | code.py | 8.0.0-beta.3\Sleeping!
Loopping!
Sleeping!
]0;🐍192.168.1.138 | Done | 8.0.0-beta.3\
Code stopped by auto-reload. Reloading soon.
soft reboot

### Description

It seams that time.sleep crashes the microcontroller after a few times that it is called.  Most times it only gets one sleep in before it does a "soft reboot"

**Comment by Neradoc** [comment]
Hi, Auto reload is normally caused by something on your computer writing to the board's drive.
Some antivirus software do that, there's an FAQ on that.
https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#code-dot-py-restarts-constantly-3108374

If that's not enough, you can go to the Adafruit forum or Discord for support questions where people might be able to help you figure it out:
https://forums.adafruit.com/
https://adafru.it/discord
