### ISSUE TITLE
Consider deleting stale branches 

### ISSUE THREAD

**Issue by MicroDev1** [adafruit/circuitpython#7243]
[These](https://github.com/adafruit/circuitpython/branches/stale) branches are multiple years old and probably haven't seen any activity for a long time.

**Comment by dhalbert** [comment]
Thank you for suggesting this. I deleted most of these. Some of these were from `micropython`, and they are no longer there, so I deleted them here. There were a few named ones by us, and I checked their commits and found the changes had been committed, so I deleted those as well.

I kept all the `x.y.z` version style branches, because they are of historical interest. I have sometimes gone back to these branches for debugging reasons.
