### ISSUE TITLE
In Python, names can not start with a number

### ISSUE THREAD

**Issue by turbinenreiter** [adafruit/circuitpython#73]
```
>>> board.
A0              A1              A2              A3
A4              A5              SCK             MOSI
MISO            0RX             1TX             SDA
SCL             D5              D6              D9
D10             D11             D12             D13
>>> board.0RX
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
>>> 
```

0RX and 1TX are not valid names. This makes it kinda hard to use UART. I still haven't figured out how I can pass in the needed Pin references.

**Comment by tannewt** [comment]
Thanks for the report! Are you using Arduino Zero? I tested it using GPS and a feather where I've given each pin two names such as D0 and RX instead of the invalid compound name. I'll fix this shortly.

You can always use `microcontroller.pin` to reference any pin. For example D0 is `microcontroller.pin.PA11`.
