### ISSUE TITLE
PyPortal TFT left hand edge getting cutoff when using case with 8.0.0 release

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#7562]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0 on 2023-02-06; Adafruit PyPortal with samd51j20
```

### Code/REPL

```python
n/a
```

### Behavior

n/a

### Description

Left hand edge of display gets cutoff when using the PyPortal with the Desktop Stand case:
https://www.adafruit.com/product/4146

Looks OK with 7.3.3.

### Additional information

See related forum thread here:
https://forums.adafruit.com/viewtopic.php?p=959876

**Comment by dhalbert** [comment]
This may be due to status bar (title bar) changes, maybe in #6473?

**Comment by tannewt** [comment]
This was a deliberate change I made. We used to leave a blank column below blinka because the terminal's top left corner was to the right of it. Now, with 8.0, the title bar terminal is to the right of blinka and the regular terminal can now be positioned below it.

I don't know what we'd want to change in CP for this.

**Comment by dhalbert** [comment]
Can the terminal TileGrid (is it a TileGrid), just be redone to be narrower and its origin repositioned? This could be done for the PyPortal in general, or we could offer a software solution (in boot.py or code.py?) for those using the case.

And maybe we should respin the case design.
