### ISSUE TITLE
bug by inspection in StateMachine.run

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7706]
### CircuitPython version

```python
main
```

### Code/REPL

```python
sm.run(array.array('H', [...]))
```

### Behavior

According to the user report on Discord, use of .run is causing the interpreter to hang.

### Additional information

A user on Discord asked about using StateMachine.run, and indicated observing problems when trying to do so.
While reading the source, I noticed that there's an apparent need to (A) check the run buffer for containing an even number of bytes and (B) divide the buffer size in bytes by 2 to give the number of instructions when calling common_hal_rp2pio_statemachine_run

I suspect a change like the following is needed:
```
diff --git a/ports/raspberrypi/bindings/rp2pio/StateMachine.c b/ports/raspberrypi/bindings/rp2pio/StateMachine.c
index ada9f46020..6a9430467b 100644
--- a/ports/raspberrypi/bindings/rp2pio/StateMachine.c
+++ b/ports/raspberrypi/bindings/rp2pio/StateMachine.c
@@ -341,7 +341,10 @@ STATIC mp_obj_t rp2pio_statemachine_run(mp_obj_t self_obj, mp_obj_t instruction_
     mp_buffer_info_t bufinfo;
     mp_get_buffer_raise(instruction_obj, &bufinfo, MP_BUFFER_READ);

-    common_hal_rp2pio_statemachine_run(self, bufinfo.buf, bufinfo.len);
+    if (bufinfo.len % 2 != 0) {
+        mp_raise_ValueError(translate("Program size invalid"));
+    }
+    common_hal_rp2pio_statemachine_run(self, bufinfo.buf, bufinfo.len / 2);
     return mp_const_none;
 }
 MP_DEFINE_CONST_FUN_OBJ_2(rp2pio_statemachine_run_obj, rp2pio_statemachine_run);
```
and we should devise a test/demo which uses "run" in this way.

**Comment by kreasteve** [comment]
I tried this:
```python
import adafruit_pioasm
import rp2pio
import time
import array
import board

test = """
.side_set 1 opt
loop:
    set y, 30   side 0
    jmp loop    side 1
    in y,32
"""

in_str = """
    mov x, y
    in x, 32
"""

asm = adafruit_pioasm.assemble(test)
in_asm = adafruit_pioasm.assemble(in_str)

sm = rp2pio.StateMachine(
    program=asm,
    frequency=2000,
    first_sideset_pin=board.LED,
    sideset_enable=True,
    auto_push=True,
)

time.sleep(1)

for i in range(2): #first run returns "30", second run "0" and the board.LED value is fixed to 1 -> statemachine does not run anymore
    sm.run(in_asm)
    time.sleep(0.1)
    buffer = array.array('L', [0])
    sm.readinto(buffer)
    print(buffer)

time.sleep(5)
```

The sm runs, the led flickers. But if the first run function is called, the sm stops.

Maybe we need an aditional `pio_sm_set_enabled(self->pio, self->state_machine, True);` in common_hal_rp2pio_statemachine_run or after the call of sm.run(...)

**Comment by kreasteve** [comment]
Why the hell is it working now?

...keep trying

**Comment by jepler** [comment]
What I think might happen if the instruction count is calculated incorrectly is this:

You have a buffer containing one instruction, but its byte length is 2:
```
>>> in_asm = adafruit_pioasm.assemble(in_str)
>>> in_asm
array('H', [16448])
>>> len(bytes(in_asm))
2
```

This means that 2 instructions will be executed; the first is the expected one, and the second is uninitialized memory.

The results could be different and unpredictable depending what the uninitialized value actually is.

There's a second potential problem. `common_hal_rp2pio_statemachine_run` may need to check for `pio_sm_is_exec_stalled` before executing an instruction. Otherwise, it could queue up the second instruction before the first has finished executing. In this case, it might cause the `in` instruction to be replaced by the uninitialized instruction.

In the sdk docs I didn't see anything mentioning a need to call `pio_sm_set_enabled` but it doesn't mean it's not needed.

**Comment by kreasteve** [comment]
> You have a buffer containing one instruction, but its byte length is 2

Maybe I don't get what you mean. `pio_sm_is_exec` takes a 16 bit integer as a instruction for the statemachine. And the `mp_buffer_info_t` could be also something other than a 16 bits integer (array).
I think I understand slightly.

What I am thinking about... Here some code snippets:
```c
// Buffer protocol
typedef struct _mp_buffer_info_t {
    void *buf;      // can be NULL if len == 0
    size_t len;     // in bytes
    int typecode;   // as per binary.h
} mp_buffer_info_t;

STATIC mp_obj_t rp2pio_statemachine_run(mp_obj_t self_obj, mp_obj_t instruction_obj) {
    rp2pio_statemachine_obj_t *self = MP_OBJ_TO_PTR(self_obj);
    check_for_deinit(self);

    mp_buffer_info_t bufinfo;
    mp_get_buffer_raise(instruction_obj, &bufinfo, MP_BUFFER_READ);

    common_hal_rp2pio_statemachine_run(self, bufinfo.buf, bufinfo.len);
    return mp_const_none;
}

void common_hal_rp2pio_statemachine_run(rp2pio_statemachine_obj_t *self, const uint16_t *instructions, size_t len) {
    for (size_t i = 0; i < len; i++) {
        pio_sm_exec(self->pio, self->state_machine, instructions[i]);
    }
}
```
`mp_get_buffer_raise` "transfers" the content of `instruction_obj` into `bufinfo`, is that right?
`bufinfo.len` is the length of the created buffer in bytecounts, isn't it?
And `common_hal_rp2pio_statemachine_run` takes a 16 bit integer "array" with the 'len' in wordcounts, isn't it?
That would mean, that `common_hal_rp2pio_statemachine_run` gets the pointer of the beginning of the `bufinfo` and executes two words instead of one.

> There's a second potential problem ... `pio_sm_is_exec_stalled`

Maybe. What I am thinking about: A stall only occurs if the instruction send with `pio_sm_exec` can stall (e.g. wait or push block). That are the instructions you should not use if you don't want to slow down the program in the sm instruction memory. Maybe its interesting to can check the stall flag with an `sm.run_stalled` property for further reasons. But I think it is not necessary for this problem.

> `pio_sm_set_enabled`

Yes, it's not needed. I have written my counter with c and it works without `pio_sm_set_enabled`.

**actual circuitpython async counter script**

Here I posted, what I really want to do and where I'm working on: https://pastebin.com/zdTtSdTu
It don't work properly. Just to get an idea.

**additional thing**

As I didn't know what sm.run() do, I wrote it like this: `sm.run("in y, 32")`
Maybe you want/can check, that the buffer is not a string. (Only for idiots like me :)

**Comment by kreasteve** [comment]
I'll give that a try tomorrow. 

Do you have an idea to prevent using a string for the parameter of run?

**Comment by jepler** [comment]
You could check that the buffer length is a multiple of two, as is done in another spot maybe in that same file. Or, you could check that the type code is `'H'` but that might be considered an incompatible change, I'm not sure. (Especially as this function in particular really didn't work at all before fixing this bug)
