### ISSUE TITLE
CP 8.0 can't connect to hidden APs

### ISSUE THREAD

**Issue by juanfra684** [adafruit/circuitpython#7935]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.3 on 2023-02-23; S2Mini with ESP32S2-S2FN4R2
```

### Code/REPL

```python
>>> import wifi
>>> import ipaddress
>>> ipv4 = ipaddress.IPv4Address("192.168.1.100")
>>> netmask = ipaddress.IPv4Address("255.255.255.0")
>>> gateway = ipaddress.IPv4Address("192.168.1.1")
>>> wifi.radio.set_ipv4_address(ipv4 = ipv4, netmask = netmask, gateway = gateway)
>>> wifi.radio.connect(os.getenv('CIRCUITPY_WIFI_SSID'), os.getenv('CIRCUITPY_WIFI_PASSWORD'))
```

### Behavior

```plain
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ConnectionError: No network with that ssid
```
The data in `settings.toml` is right. CP can't connect to the AP because it is hidden.

### Additional information

Could you enable the scan of hidden networks?. IIRC, MicroPython has support for it at least for the ESP32.

**Comment by anecdata** [comment]
I'm curious if specifying the BSSID (and maybe channel) of the hidden AP matters with the current API.

Looks like there's a scan config option to show hidden
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-guides/wifi.html#scan-configuration
which we'd probably do where we allow connect to specify BSSID and / or channel
https://github.com/adafruit/circuitpython/blob/fa9b59d14c156b614410fa26a6228febc207131e/ports/espressif/common-hal/wifi/Radio.c#L304
not sure of whether policy should be always allow, or add a parameter ro `wifi.radio.connect()`

**Comment by dhalbert** [comment]
You can give a channel number to `connect()`: https://docs.circuitpython.org/en/latest/shared-bindings/wifi/index.html#wifi.Radio.connect.

The range of channels 1-11 is geographical.

**Comment by anecdata** [comment]
circuitpython doesn't restrict channel tighter than 1-13 due to its international audience, but if the `espressif` SDK limits connect() to 1-11, perhaps we should too. Not sure what `raspberrypi` SDK supports offhand.

I'm pretty sure APs can be created on 1-13, and wifi Monitor can receive 1-13. I see (U.S.) quite a few devices using channel 12, little to none on channel 13. Channels 12 and 13 have use [limitations](https://en.wikipedia.org/wiki/List_of_WLAN_channels#ref_B) in the U.S.
