### ISSUE TITLE
High temperature reading when using Liatris from Splitkb

### ISSUE THREAD

**Issue by dasmikko** [adafruit/circuitpython#8267]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.2 on 2023-08-01; splitkb.com Liatris with rp2040
```

### Code/REPL

```python
import microcontroller
print(microcontroller.cpu.temperature)
```

### Behavior

Reports between 68-80 degrees, when the room temperature is around 20 degrees celcius

### Description

I have a feeling it reports a wrong temperature, or fahrenheit.

**Comment by jepler** [comment]
a CPU temperature sensor is designed to measure temperature at some point inside the CPU chip itself, not the ambient temperature. This can be quite a bit above the ambient temperature.

https://learn.adafruit.com/adafruit-feather-rp2040-pico/cpu-temperature

Here's what we say about it, generally speaking for all circuitpython boards:
> There is a temperature sensor built into the CPU on your microcontroller board. It reads the internal CPU temperature, which varies depending on how long the board has been running or how intense your code is.

fwiw I just plugged in an Adafruit Qt Py RP2040 and as quickly as I could after starting it the temperature was reporte as 30.4. As I've been writing this response over the last ~10 minutes while I've been composing this message it's risen to 37.4. This inside a 3D printed enclosure, ambient temperature around 26°C, and the board is otherwise idle with no LEDs on and driving no loads.

80 degrees seems high but RP2040 datasheet gives the case operating temperature as up to 85°C so this is not hot enough to cause damage to the RP2040 chip. (https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf page 617)

That said, if you're concerned about the temperature of your device you can try
 * measuring the temperature soon after power on when you know the device is initially at ambient temperature
 * using a different programming environment to measure the temperature
 * inquiring with the board maker whether the temperature you're measuring is considered normal.
