### ISSUE TITLE
Revamp SPI display C module

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#872]
It should handle refreshing the display over SPI in the background.

**Comment by deshipu** [comment]
The trivial (and I think most common) case is when the display is the only device on the SPI bus — you can just tie CS to GND then permanently and only block when a transfer is requested when the previous transfer is still happening. All displays that Adafruit carries support that (perhaps with the exception of the SHARP displays, which as haven't been able to get to work as of yet). That case also lets us optimize busdevice a bit, because we don't have to re-set the speed and polarity each time, or handle the locking — basically we can keep the bus locked all the time. I do that for µGame and it helps even without non-blocking transfers.
The non-trivial case when there are multiple devices on the SPI bus would require some sort of built-in CS pin handling, either by the peripheral itself (ESP8266 can do it, not sure about SAMD), or by the C code in an interrupt.

**Comment by deshipu** [comment]
Perhaps this is a good moment to re-implement busdevice in C?

**Comment by tannewt** [comment]
This is done. Displays now refresh automatically.

**Comment by ladyada** [comment]
🥇
