### ISSUE TITLE
"board" module still gets incorrect docs

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#9465]
### CircuitPython version

```python
9.1.x, main
```

### Code/REPL

```python
# readthedocs problem
```

### Behavior

https://docs.circuitpython.org/en/latest/shared-bindings/board/index.html is empty, when it should have content

### Description

During readthedocs, the empty `__init__.py` is used for generating the documentation of this module, rather than the `__init__.pyi` file:

```
[AutoAPI] Reading files... [ 47%] /home/docs/checkouts/readthedocs.org/user_builds/circuitpython/checkouts/9.1.x/circuitpython-stubs/board/__init__.py
```

### Additional information

I thought I had fixed this in #9431 but apparently my fix was incorrect.

**Comment by jepler** [comment]
It's still wrong in main branch now that it's been merged up: https://docs.circuitpython.org/en/latest/shared-bindings/board/index.html

I am perplexed but don't have any time to work on it now.

**Comment by jepler** [comment]
or maybe I needed to shift-reload. can someone else take a look and close if appropriate? I'm at my wits' end.

**Comment by FoamyGuy** [comment]
It appears to me that this is resolved now. I see the content inside the board module docs page on the currently live docs. I also saw an actions run that was previously failing due to this that was able to pass now.

![image](https://github.com/user-attachments/assets/b375aaef-6331-483b-aa36-649143aae28c)
