### ISSUE TITLE
RP2350: Issue with read current pin state

### ISSUE THREAD

**Issue by StefanDraeger** [adafruit/circuitpython#9574]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.0-alpha.2351 on 2024-08-22; Raspberry Pi Pico 2 with rp2350a
```

### Code/REPL

```python
import board
import time
import board
from digitalio import DigitalInOut, Direction, Pull

tasterSchwarz = DigitalInOut(board.GP28)
tasterSchwarz.direction = Direction.INPUT
tasterSchwarz.pull = Pull.DOWN

while True:
        if tasterSchwarz.value == 1:
            print("key down")
```

### Behavior

The state of the pin doesnt change after set it to HIGH / 1

### Description

Circuit: 
GP28 > Button Pin 1
3.3V (OUT) > Button Pin 2
If I press the button once an relaese this, the state doesnt change its still stay as on.

### Additional information

Testet with the new Raspberry Pi Pico 2 - RP2350A device,
retestet with the old Version Raspberry Pi Pico - RP2040

The behavior of the old modell is correct, so the state of the pin change after release the button.

**Comment by dhalbert** [comment]
This is a hardware bug in the RP2350, unfortunately. See #9541 and https://github.com/raspberrypi/pico-feedback/issues/401. Also see https://forums.raspberrypi.com/viewtopic.php?t=375631. We are awaiting further information for Raspberry Pi about their path forward on this.

Closing this in favor of #9541, but thank you for reporting, so that we know that typical users are hitting this problem as well. Multiple people and companies are encountering
